name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker-hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build Docker Image
        id: build-docker-image
        run: |
          ls -la  
          docker build -f Dockerfile -t $DOCKERHUB_USERNAME/sauter-university:latest .

      - name: Push Docker Image
        id: push-docker-image
        run: |
          docker push $DOCKERHUB_USERNAME/sauter-university:latest
